# ──────────────────────────────────────────────────────
#  nginx/Dockerfile
#  Imagen Nginx con configuración personalizada para TapoMon.
# ──────────────────────────────────────────────────────
FROM nginx:1.27-alpine

# Copiar configuración personalizada
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
